### ISSUE TITLE
Pin version of requirements.txt dependencies?

### ISSUE THREAD

**Issue by traversaro** [ami-iit/paper_sartore_2022_humanoids_ergonomic_design#3]
As PyPI is a rolling release distribution (as opposed to stable distribution like Ubuntu), it is possible that in the future a new version of scipy or casadi that breaks your softwarw comes out. For this reason, could it make sense to pin the version of all the packages listed in `requirements.txt`?

**Comment by traversaro** [comment]
cc @CarlottaSartore

**Comment by CarlottaSartore** [comment]
Thanks @traversaro  ! I totally agree, I've missed it ! 

Done in https://github.com/ami-iit/paper_sartore_2022_humanoids_ergonomic_design/commit/949c614c778b760a705209e9192e23d3143367bb 

Closing issue !
